
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
management:
  tracing:
    sampling:
      probability: 1.0
#  zipkin:
#    base-url: http://146.190.96.231:9411
#  sleuth:
#    sampler:
#      probability: 1.0
spring:
  zipkin:
    base-url: http://146.190.96.231:9411
  sleuth:
    sampler:
      probability: 1.0
