#server:
#  port: 8081
#
#spring:
#  application:
#    name: department-service
#eureka:
#  instance:
#    hostname: localhost
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: department-service
  config:
    import: "optional:configserver:http://localhost:8088"
  cloud:
    loadbalancer:
      enabled: true
server:
  port: 8081